# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}: {
  rome = {
    pname = "rome";
    version = "665bb9d810b4ebf4ea82b72df20ad79b8fa3a3d0";
    src = fetchgit {
      url = "https://github.com/rome/tools";
      rev = "665bb9d810b4ebf4ea82b72df20ad79b8fa3a3d0";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-SKq86nbTmMnSuRwCkrpNywPLUAMhf5pS3bmtFe4YuPE=";
    };
    date = "2023-05-31";
  };
  wemake-python-styleguide = {
    pname = "wemake-python-styleguide";
    version = "7a112bb8b95a59027611af026a4807871f7e323e";
    src = fetchgit {
      url = "https://github.com/wemake-services/wemake-python-styleguide";
      rev = "7a112bb8b95a59027611af026a4807871f7e323e";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-EQ6cgie2Rxo4hXkcWSKgToULWFWWF/aSh/BennJiyUo=";
    };
    date = "2023-05-31";
  };
}
