# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}: {
  rome = {
    pname = "rome";
    version = "ab3524889a0dd82d640797cbd2c5b2fadf246d70";
    src = fetchgit {
      url = "https://github.com/rome/tools";
      rev = "ab3524889a0dd82d640797cbd2c5b2fadf246d70";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-Cy0R1bYWA+p6pLeH5XzsNcYx89+tcSt3RA4RRrW7fLs=";
    };
    date = "2023-05-19";
  };
}
