# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}: {
  wemake-python-styleguide = {
    pname = "wemake-python-styleguide";
    version = "69bb6f47aeb0f6a74c05e05960fc3da5b33edc6b";
    src = fetchgit {
      url = "https://github.com/wemake-services/wemake-python-styleguide";
      rev = "69bb6f47aeb0f6a74c05e05960fc3da5b33edc6b";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-mBBkcwsIX6VqtRzgKm7FjdkaArD/IgEMz7+UwlMyMV4=";
    };
    date = "2023-06-02";
  };
}
